In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
from sklearn.model_selection import train_test_split

In [37]:
data = pd.read_csv("online_retail_II.csv")

In [38]:
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [39]:
datacopy = data[data["Quantity"] > 0]

In [40]:
datacopy.head()
data = datacopy

In [41]:
topsels = data.nlargest(250, "Quantity")
topsels.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1065882,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom
587080,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom
90857,497946,37410,BLACK AND WHITE PAISLEY FLOWER MUG,19152,2010-02-15 11:57:00,0.10,13902.0,Denmark
127166,501534,21099,SET/6 STRAWBERRY PAPER CUPS,12960,2010-03-17 13:09:00,0.10,13902.0,Denmark
127168,501534,21091,SET/6 WOODLAND PAPER PLATES,12960,2010-03-17 13:09:00,0.10,13902.0,Denmark

In [42]:
data.info()

<class 'pandas.DataFrame'>
Index: 1044421 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1044421 non-null  str
 1   StockCode    1044421 non-null  str
 2   Description  1042728 non-null  str
 3   Quantity     1044421 non-null  int64
 4   InvoiceDate  1044421 non-null  str
 5   Price        1044421 non-null  float64
 6   Customer ID  805620 non-null   float64
 7   Country      1044421 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 71.7 MB

In [43]:
data.shape

(1044421, 8)

In [44]:
data.isnull().sum()

Invoice             0
StockCode           0
Description      1693
Quantity            0
InvoiceDate         0
Price               0
Customer ID    238801
Country             0
dtype: int64

In [45]:
data[data.isnull().any(axis=1)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1066997,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066998,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066999,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
1067000,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
1067001,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

In [46]:
topsels.isnull().sum()

Invoice         0
StockCode       0
Description    29
Quantity        0
InvoiceDate     0
Price           0
Customer ID    38
Country         0
dtype: int64

In [47]:
topsels = topsels.dropna()
topsels.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
577594,540689,22469,HEART OF WICKER SMALL,1356,2011-01-11 08:43:00,1.93,17450.0,United Kingdom
711380,552833,23167,SMALL CERAMIC TOP STORAGE JAR,1350,2011-05-11 14:14:00,0.69,18133.0,United Kingdom
90859,497946,85197,SET OF 12 MINI BUNNIES IN A BUCKET,1344,2010-02-15 11:57:00,0.25,13902.0,Denmark
298930,518505,37444A,YELLOW BREAKFAST CUP AND SAUCER,1308,2010-08-09 13:10:00,0.13,14277.0,France
358752,524174,37444A,YELLOW BREAKFAST CUP AND SAUCER,1308,2010-09-27 16:30:00,0.13,13687.0,United Kingdom

In [48]:
topsels.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [49]:
topsels.info()

<class 'pandas.DataFrame'>
Index: 212 entries, 1065882 to 358752
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Invoice      212 non-null    str
 1   StockCode    212 non-null    str
 2   Description  212 non-null    str
 3   Quantity     212 non-null    int64
 4   InvoiceDate  212 non-null    str
 5   Price        212 non-null    float64
 6   Customer ID  212 non-null    float64
 7   Country      212 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 14.9 KB

In [50]:
topsels['StockCode'].count()

np.int64(212)

In [51]:
topsels.describe()

           Quantity       Price   Customer ID
count    212.000000  212.000000    212.000000
mean    3992.400943    0.496745  14940.735849
std     7678.023391    0.682248   1679.026435
min     1308.000000    0.000000  12346.000000
25%     1509.000000    0.130000  13687.000000
50%     2400.000000    0.190000  14277.000000
75%     4050.000000    0.550000  16333.000000
max    80995.000000    5.060000  18133.000000

In [52]:
topsels.shape

(212, 8)

In [53]:
topsels["Country"].unique()

<StringArray>
['United Kingdom', 'Denmark', 'France', 'Netherlands', 'Japan', 'EIRE',
 'Sweden']
Length: 7, dtype: str

In [54]:
topsels['Country'].value_counts()

Country
United Kingdom    138
Denmark            39
France             21
Netherlands         4
Sweden              4
Japan               3
EIRE                3
Name: count, dtype: int64