In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv("online_retail_II.csv")

In [4]:
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
data = data["Quantity"] > 0

In [20]:
data["Quantity"] > 0

KeyError: 'Quantity'

In [ ]:
topsels = data.nlargest(250, "Quantity")
topsels.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
748142,C556445,M,Manual,-1,2011-06-10 15:31:00,38970.00,15098.0,United Kingdom
241824,C512770,M,Manual,-1,2010-06-17 16:52:00,25111.09,17399.0,United Kingdom
241827,512771,M,Manual,1,2010-06-17 16:53:00,25111.09,NaN,United Kingdom
320581,C520667,BANK CHARGES,Bank Charges,-1,2010-08-27 13:42:00,18910.69,NaN,United Kingdom
1050063,C580605,AMAZONFEE,AMAZON FEE,-1,2011-12-05 11:36:00,17836.46,NaN,United Kingdom

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 65.1 MB

In [7]:
data.shape

(1067371, 8)

In [8]:
data.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [9]:
data[data.isnull().any(axis=1)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1066997,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066998,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066999,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
1067000,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
1067001,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

In [10]:
topsels.isnull().sum()

Invoice          0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
Price            0
Customer ID    137
Country          0
dtype: int64

In [11]:
topsels = topsels.dropna()
topsels.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
992356,C576338,CRUK,CRUK Commission,-1,2011-11-14 15:27:00,1038.75,14096.0,United Kingdom
233553,C511999,M,Manual,-1,2010-06-11 15:44:00,1000.63,14255.0,United Kingdom
233555,512002,M,Manual,1,2010-06-11 15:54:00,1000.63,14255.0,United Kingdom
1033982,C579195,CRUK,CRUK Commission,-1,2011-11-28 15:54:00,987.14,14096.0,United Kingdom
51493,494042,M,Manual,1,2010-01-11 11:57:00,975.11,12510.0,Spain

In [12]:
topsels.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [13]:
topsels.info()

<class 'pandas.DataFrame'>
Index: 113 entries, 748142 to 51493
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Invoice      113 non-null    str
 1   StockCode    113 non-null    str
 2   Description  113 non-null    str
 3   Quantity     113 non-null    int64
 4   InvoiceDate  113 non-null    str
 5   Price        113 non-null    float64
 6   Customer ID  113 non-null    float64
 7   Country      113 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 7.9 KB

In [14]:
topsels['StockCode'].count()

np.int64(113)

In [15]:
topsels.describe()

         Quantity         Price   Customer ID
count  113.000000    113.000000    113.000000
mean    -0.265487   3616.984867  14599.619469
std      0.982141   4733.477370   1635.742990
min     -2.000000    975.110000  12380.000000
25%     -1.000000   1269.510000  12918.000000
50%     -1.000000   2053.070000  14156.000000
75%      1.000000   3949.320000  15581.000000
max      1.000000  38970.000000  18102.000000

In [16]:
topsels.shape

(113, 8)

In [17]:
topsels["Country"].unique()

<StringArray>
['United Kingdom',         'Norway',         'France',      'Singapore',
           'EIRE',          'Malta',          'Spain',        'Belgium',
       'Portugal',    'Unspecified']
Length: 10, dtype: str

In [18]:
topsels['Country'].value_counts()

Country
United Kingdom    64
EIRE              14
Singapore         10
France             8
Norway             5
Portugal           4
Spain              3
Malta              2
Belgium            2
Unspecified        1
Name: count, dtype: int64