In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("online_retail_II.csv")

In [3]:
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
topsels = data.nlargest(100, "Price")
topsels.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
748142,C556445,M,Manual,-1,2011-06-10 15:31:00,38970.00,15098.0,United Kingdom
241824,C512770,M,Manual,-1,2010-06-17 16:52:00,25111.09,17399.0,United Kingdom
241827,512771,M,Manual,1,2010-06-17 16:53:00,25111.09,NaN,United Kingdom
320581,C520667,BANK CHARGES,Bank Charges,-1,2010-08-27 13:42:00,18910.69,NaN,United Kingdom
1050063,C580605,AMAZONFEE,AMAZON FEE,-1,2011-12-05 11:36:00,17836.46,NaN,United Kingdom

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 65.1 MB

In [6]:
data.shape

(1067371, 8)

In [7]:
data.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [8]:
data[data.isnull().any(axis=1)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1066997,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066998,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066999,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
1067000,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
1067001,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

In [9]:
topsels.isnull().sum()

Invoice         0
StockCode       0
Description     0
Quantity        0
InvoiceDate     0
Price           0
Customer ID    58
Country         0
dtype: int64

In [12]:
topsels = topsels.dropna()
topsels.tail(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
793488,C560372,M,Manual,-1,2011-07-18 12:26:00,4287.63,17448.0,United Kingdom
166299,C505145,M,Manual,-1,2010-04-20 11:25:00,4217.59,16151.0,United Kingdom
947835,573077,M,Manual,1,2011-10-27 14:13:00,4161.06,12536.0,France
947836,C573079,M,Manual,-2,2011-10-27 14:15:00,4161.06,12536.0,France
947838,573080,M,Manual,1,2011-10-27 14:20:00,4161.06,12536.0,France
931865,C571750,M,Manual,-1,2011-10-19 11:16:00,3949.32,12744.0,Singapore
931867,571751,M,Manual,1,2011-10-19 11:18:00,3949.32,12744.0,Singapore
288684,C517480,M,Manual,-1,2010-07-29 12:24:00,3610.50,14028.0,United Kingdom
288706,517483,M,Manual,1,2010-07-29 12:29:00,3610.50,12737.0,France
272635,C515886,M,Manual,-1,2010-07-15 12:04:00,3580.80,18102.0,United Kingdom
241696,C512752,M,Manual,-1,2010-06-17 15:23:00,3248.86,18023.0,United Kingdom
819303,C562647,M,Manual,-1,2011-08-08 12:56:00,3155.95,15502.0,United Kingdom
900002,569382,M,Manual,1,2011-10-03 16:44:00,3155.95,15502.0,United Kingdom
796612,C560647,M,Manual,-1,2011-07-20 11:31:00,3060.60,18102.0,United Kingdom
342146,C522795,M,Manual,-1,2010-09-16 15:09:00,2769.90,14063.0,United Kingdom
358670,524162,M,Manual,1,2010-09-27 16:18:00,2769.90,14063.0,United Kingdom
372863,C525400,M,Manual,-1,2010-10-05 11:52:00,2769.90,14063.0,United Kingdom
418866,C529353,M,Manual,-1,2010-10-28 09:41:00,2736.16,14156.0,EIRE
418886,529356,M,Manual,1,2010-10-28 09:44:00,2736.16,14156.0,EIRE
389334,C526858,M,Manual,-1,2010-10-13 13:01:00,2667.88,15202.0,United Kingdom

In [11]:
topsels.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [ ]:
topsels.info()